spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/spring_data_jpa
    url: jdbc:postgresql://postgresql-prod/docker_db_demo
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  # spring data jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
