spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    username: postgres
    password: postgres@admin
    driver-class-name: org.postgresql.Driver

  # spring data jpa configuration
  jpa:
    hibernate:
      ddl-auto: 'update'
    database: postgresql
    show-sql: true



## MySQL

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring_jpa
#    username: root
#    password: mysql@Admin1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  # spring data jpa configuration
#  jpa:
#    hibernate:
#      ddl-auto: 'create-drop'
#    database: mysql
#    show-sql: true